### ISSUE TITLE
Add PR template to require PR authors to include necessary JSON Schema updates

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/geoparquet#102]
With #64 we are now saying that the JSON schema file is a core part of the spec, so we should ensure that any PR that changes behavior always updates both the spec and the schema file. I think the easiest way to do this is a just a checkbox nudge on any PR, to help us remember, though I'm open to other ideas. 

I suppose that in turn will force us to update examples, but that seems like a good thing.

**Comment by brendan-ward** [comment]
PR process question re: #104: when a contributor updates the spec, should they also update the version number in various places as part of that PR?  On the one hand, it seems that the version isn't bumped until ratified by approving PRs (of which there may be multiple incremental updates to the spec prior to the next minor version), but on the other it seems like extra work to bump that later like in #104.

**Comment by cholmes** [comment]
I lean towards bumping on release. I want to try to write up a 'release process' document like https://github.com/radiantearth/stac-spec/blob/master/process.md#release-process just to have a check-list to make sure we do everything.

I think it could be nice to have a 'version release PR' - like where we do the version bumps in the readme, spec, examples & scripts all in one PR. And then ideally that PR would need approval by some high percentage of 'core contributors' as a vote that 'this is ready for release'. Release process would be merging that PR and then cutting the release.

**Comment by cholmes** [comment]
I don't think we'll do this for 1.1
