### ISSUE TITLE
Versioning and changes

### ISSUE THREAD

**Issue by karunakar2** [opengeospatial/geoparquet#117]
Hello devs, maintainers and users,
Good day.

This isn't an tech issue per se, however,
I see couple of points here from my experience, discussions 
and also given readme.md forms part of the repo,
1. Since backward compatibility isn't promised under 0.x; from a naïve user point, would this mean change in programming interface or at the storage file level.
2. Given gdal (3.5) supports the (geo) parquet format already, files generated out of 0.4 would be future readable? 
ref for parquet "https://github.com/apache/parquet-format"

Hope the answers make it to the landing page.

Thanks,

**Comment by cholmes** [comment]
Hey @karunakar2 - apologies for the slow response. 

So in the 0.x  / alpha stage of things the core group is not able to provide an forward compatibility promises - as long as we're in 0.x we reserve the right to make backwards incompatible changes, though we don't anticipate any and certainly value backwards compatibility so we'll do our best. And that could be a change in the programming interface or the storage file level (though would more likely be in the metadata of the storage file, we likely wouldn't change wkb). The good news is we'll soon be going to 'beta.1', see https://github.com/opengeospatial/geoparquet/discussions/122 I still don't think we'd fully promise that beta.1 will be backwards compatible, but we'll try really hard to be sure that it can. 

So most likely files generated out of 0.4 will be future readable - we don't anticipate any changes that would make it not readable, but don't want to commit to that till 1.0.0. At that point we'll use SemVer, and any forward compatible change will mean a 1.x release, and any backwards incompatible change will be a major version bump, like to 2.0.

**Comment by jorisvandenbossche** [comment]
To add one thing to what @cholmes already said: even in the unlikely case there would still be a change before 1.0.0, _implementations_ can still support reading older versions as well. For example, speaking for the GeoPandas reader, I think we would certainly support reading <1.0 files for quite some time.
