### ISSUE TITLE
Validator improvements

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/geoparquet#124]
For 1.0.0 we should have a validator that:

1) Tests not just the metadata but looks at the data itself to make sure it matches the metadata
2) Is user-friendly, not requiring python. Ideally a web-page and/or an easily installable binary.

This could be building on the current validator in this repo, or could be a new project we reference, but we want to be sure something exists, so putting this issue in to track it.

**Comment by kylebarron** [comment]
> Ideally a web-page

I think that should be possible; [`parquet-wasm`](https://github.com/kylebarron/parquet-wasm) can read just a file's metadata without reading any of the data, so we should at least be able to load the geo metadata from a remote parquet file (or one dragged in) and run a javascript jsonschema checker on it.

I could show how to use the `parquet-wasm` api, but I don't think I'll have the time to set up the entire webpage

**Comment by mrisney** [comment]
Very happy to hear that [pq](https://github.com/kylebarron/parquet-wasm) is being consider. Also not sure that "gecommands" are even something that is being thought of, but when using the Geospatial commands of Reddis. The brevity of the commands are very easy to use :  "[GEODIST](https://redis.io/commands/geodist) cars my-car robins-car"

**Comment by jorisvandenbossche** [comment]
If we want to fully validate a file (i.e. do more than the current validator checking the json schema), we will have to parse the WKB values in the geometry columns.

**Comment by m-mohr** [comment]
Just a random thought as JSON Schema can't provide this:
The validator should check whether the value of primary_geometry exists as a property key in columns.

**Comment by cholmes** [comment]
Closing this, as we've got good validators that check the data itself with [GPQ](https://github.com/planetlabs/gpq) and GDAL/OGR.

GPQ is an easily installable binary, and then you just run `gpq validate`. I think @tschaub has a plan to put gpq in wasm to do a javascript viewer, but we decided to not block on 1.0 for that.
