### ISSUE TITLE
Update JSON Schema version?

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/geoparquet#127]
Just a random thing I noticed while looking through the repo: Not sure whether this comes from the fact that all STAC JSON Schemas are still draft 7, but you may want to consider updating to a more recent version. That should make it a bit more future-proof as you never know when the old JSON Schema versions will be dropped from libraries. Draft-7 is from March 2018 and has been superseeded by draft-2019-09, which itself for superseeded by draft-2020-12.

You are actually already partially into 2019-09 as for example the $defs keyword in the schema was only added in this version.

**Comment by kylebarron** [comment]
> On the other hand, the referenced PROJJSON schema is also draft-7 so to not mix things too much, keep it conistent?

Seems better to be consistent with theirs? Maybe we should talk to projjson about updating their schema version?

**Comment by m-mohr** [comment]
Yeah, I mean it's all a snowball effect, but we may need to start somewhere. Once PROJJSON updates to a newer version the mix of versions will appear in STAC, for example, where we are still on draft-7 and there we'd need to update dozens of schemas etc. The GeoJSON schemas are also still draft-7... ;-)
