### ISSUE TITLE
Potential JSON Schema issues

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/geoparquet#129]
Some potential improvements and/or issues in the JSON Schema:

- [x] `$defs` keyword in the schema was only added in draft 2019-09 (see also #127 )
- [x] `additionalProperties: true` is the default and could be removed
- [x] `"patternProperties":`  with a pattern `".*"` is basically equivalent to additionalProperties and thus can be simplified a bit.
- [x] `"enum": ["WKB"]` is equivalent to `"const": "WKB"`, the same applies to `"enum": ["counterclockwise"]`
- [x] PROJJSON has a new schema version, 0.5
- [x] The bbox schema looks weird. Are more than 4 values allowed? Right now it would allow [0,1,2,3,"asdsad"]. Could probably also be simplified using min/maxItems... I think you were looking for something like `"items": {"type": "number"}, "minItems": 4`
- [x] By the way, the spec says `double` for epoch, but this is not enforced in the schema and could be an int (or should this be "number" in the spec?)
- [x] I understand the spec that you can either specify an array of geometry types **or** a single geometry type as string **or** `Unknown` (so always as a string, not in an array). If this is the case, the schema doesn't check it. `["Polygon", "Unknown"]` is valid.
- [x] The Z suffix to the geometry types is not part of the JSON Schema it seems

Happy to work on PRs, just let me know whether all this is correctly captured.

**Comment by jorisvandenbossche** [comment]
I am not very familiar with JSON schema details, but that all sounds correct from the geoparquet side.

> The bbox schema looks weird. Are more than 4 values allowed? Right now it would allow [0,1,2,3,"asdsad"]. Could probably also be simplified using min/maxItems... I think you were looking for something like `"items": {"type": "number"}, "minItems": 4`

I am currently updating this field in https://github.com/opengeospatial/geoparquet/pull/88, so your feedback there is certainly welcome! (we are basically already doing something with items and minItems now, just spelling out the 4 or 6 values explicitly)


> `"enum": ["WKB"]` is equivalent to `"const": "WKB"`, the same applies to `"enum": ["counterclockwise"]`

Although it is not the case right now, but we are planning to add more options in the future, so can maybe keep it like that? (although also the enum wouldn't allow any other value right now, so it wouldn't really matter)

**Comment by m-mohr** [comment]
Okay, I'll draft a PR.

> I am currently updating this field in #88, so your feedback there is certainly welcome!

Done.

> 
> > `"enum": ["WKB"]` is equivalent to `"const": "WKB"`, the same applies to `"enum": ["counterclockwise"]`
> 
> Although it is not the case right now, but we are planning to add more options in the future, so can maybe keep it like that? (although also the enum wouldn't allow any other value right now, so it wouldn't really matter)

Cou can always change it back to enum once you've decided to add a new option. :-)

**Comment by cholmes** [comment]
Call 11/7 - Merging this should block on #134, just to make sure it's doing what we think it's doing. 

It'd also be good to break up #131 into multiple PR's. @tschaub will do the geometry updates in a new PR.

**Comment by tschaub** [comment]
#140 proposes changes to the geometry types.
