### ISSUE TITLE
Declare `Z` in the geometry type?

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/geoparquet#132]
Do we need to declare `Z` in the geometry type? It might make it a little harder on the writer side

_Originally posted by @kylebarron in https://github.com/opengeospatial/geoparquet/pull/131#discussion_r1004712064_

**Comment by tschaub** [comment]
I'd be in favor of removing this removing this language:

> In case of 3D geometries, a " Z" suffix gets added (e.g. "Point Z")

I suppose someone could check the length of the `bbox` if they wanted to know how many dimensions they might encounter in coordinate values.

**Comment by rouault** [comment]
> `` if they wanted to know how many dimensions they might encounter in coordinate values.

if M support is added someday, checking the bbox length will not be enough to distinguish Z from M.

**Comment by tschaub** [comment]
@rouault - Do you think it is important to know if the geometry includes Z?  Curious if there are cases where not all positions have Z (and uncertain what this would mean for parsers that use this hint).

**Comment by rouault** [comment]
> Do you think it is important to know if the geometry includes Z?

With my GDAL hat on, yes. There are definitely formats to which you could convert GeoParquet that need to distinguish upfront if geometries are going to be 2D or 3D. PostGIS is a prominent one. If that's not communicated upfront, the OGR Parquet driver would need to read the first feature (and possibly more features if the first ones have NULL geometries) to be able to guess the dimension.
Mix of dimensions inside a layer is probably less common, and could be solved by declaring [ "Polygon", "PolygonZ" ] as geometry_type.

**Comment by cholmes** [comment]
Call 117 - We need to update the schema to reflect the spec, but general consensus seems to be we should do this.
