### ISSUE TITLE
Geometry types

### ISSUE THREAD

**Issue by tschaub** [opengeospatial/geoparquet#133]
Currently, the `geometry_type` metadata property can be a string or an array of strings.  I'm wondering if this flexibility is really necessary.  When parsing this metadata into a struct, it can make things simpler to have a single type for the value.  

In addition, instead of the string `"Unknown"`, an empty array could represent unknown geometry types.

If an array sounds good, I think the name `geometry_types` also makes sense.  Basically, I'm wondering if there would be support for this instead:
```json
{
  "geometry_types": {
    "description": "The geometry types of all geometries, or an empty array if they are not known.",
    "type": "array",
    "items": {
      "type": "string",
      "pattern": "^(GeometryCollection|(Multi)?(Point|LineString|Polygon))( Z)?$"
    }
  }
}
```

**Comment by jorisvandenbossche** [comment]
> In addition, instead of the string `"Unknown"`, an empty array could represent unknown geometry types.

Some discussion about "Unknown" happened in https://github.com/opengeospatial/geoparquet/issues/41. Although we mostly discussed about whether we needed the concept (versus making the field optional), not how to indicate it (as "Unknown" or []). 

Personally I find "Unknown" a bit more explicit (and maps to what eg GDAL and flatgeobuf do), but _if_ we go with only allowing an array of values, it's certainly the easier specification.
