### ISSUE TITLE
Clarify WKB encoding type

### ISSUE THREAD

**Issue by TomAugspurger** [opengeospatial/geoparquet#14]
There are various types of WKB encoding. We should clarify exactly what flavor of WKB is expected (strict, extended, ...).

https://libgeos.org/specifications/wkb/

**Comment by TomAugspurger** [comment]
According to https://libgeos.org/specifications/wkb/

> Standard WKB supports two-dimensional geometry, and is a proper subset of both extended WKB and ISO WKB.

Are we OK with that limitation?

**Comment by cholmes** [comment]
Discussion on call is that we are ok with that limitation for 0.1, and then discuss in future iso and ewkb as options.
