### ISSUE TITLE
Propose and document release process

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/geoparquet#146]
We should have a clear cookbook of how we cut a new release.

**Comment by tschaub** [comment]
I am hoping we can get in #159 before doing this.  That change removes 4 places that the version identifier is repeated and merging it will help simplify the release process.

**Comment by tschaub** [comment]
I've added a wiki page with the [release process](https://github.com/opengeospatial/geoparquet/wiki/Release-Process).  I followed this process in #161, and here is the resulting release: [v1.0.0-beta.1](https://github.com/opengeospatial/geoparquet/releases/tag/v1.0.0-beta.1).
