### ISSUE TITLE
make website to share info about geoparquet

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/geoparquet#148]
* Include implementations here (link from website)
* Consider publishing example files (like nz buildings) as part of the spec 'publish' step.

**Comment by tschaub** [comment]
Website repo: https://github.com/geoparquet/geoparquet.github.io

Successful commits to the `main` branch of that repo get deployed to https://geoparquet.org/.  The spec and schema for releases in this repo are deployed along with the site (e.g. v0.4.0 [spec](https://geoparquet.org/releases/v0.4.0/) and [schema](https://geoparquet.org/releases/v0.4.0/schema.json)).

The site is intentionally unstyled right now (so, ugly).  We can continue to add content and then make a nice theme later.  The site is built with [11ty](https://www.11ty.dev/) (the static site generator from Netlify).  We're using GitHub Pages to host the site.

**Comment by tschaub** [comment]
Calling this done.  We can continue to make it prettier over time.
