### ISSUE TITLE
value not present vs null

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/geoparquet#157]
From experience in STAC and openEO, it seems some implementations/programming languages have a hard time to distinguish between "not present" and "null". Specifying different meanings for null and not present as for `crs` (unknown / CRS:84) might be a bad idea. Therefore, I'm putting out for discussion whether it's a good idea to do this and maybe instead use "unknown" as string or so instead of null?

**Comment by jorisvandenbossche** [comment]
I don't have a strong opinion about how we exactly represent this, except for that I want there is _some_ way to indicate that the CRS is unknown. 

In Python, it's very easy/natural to use null/None, so I can't judge about the difficulties it gives. Changing it to use "unknown" is not forward compatible (older readers will fail on files with this new value)

**Comment by m-mohr** [comment]
Closing, didn't seem overly relevant to implementors yet.
