### ISSUE TITLE
WKT support for 3/4D using Z and/or M

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/geoparquet#168]
In the draft Geoparquet  specification, in the “geometry-types” section, the use of the “Z” suffix to indicate 3D data is mandated, and the “M” suffix for other coordinate system is not yet supported. As some OGC Standards (e.g. API-EDR v1.0.1, with V1.1 and V1.2 in the pipeline) use both suffices, perhaps clear guideline or standard could be established for combinations, such as “ZM”, “MZ”, etc., and specifically whether a preceding space is required or expected. 

API-EDR has assumed that no leading spaces are expected of a suffix, but does not state an explicit requirement.  Other software has assumed no spaces is the accepted syntax.

This may not seem very important, but is undoubtedly a barrier to interoperability. Perhaps alignment with this should be explicitly mentioned in the Charter, or in a workplan annex.

**Comment by chris-little** [comment]
@jorisvandenbossche The EDR API Standard WG didn't realise having a space was an option. Possibly it was caused by multi-lingual problems, as the original proposal to use the `Z` and `M` options came from Chinese speakers. Spaces have less importance in their character sequences compared to alphabetic strings.

When the issue was raised last year in the EDR API SWG, we looked at current practice, and there was no clear guidance. We agreed that no spaces would make for slightly easier unambiguous parsing. We also unconsciously assumed that `Z` always came before `M`. And we consciously chose `M` to always mean a time coordinate.

The OGC original spec contains:
`7.2.6 Examples
Examples of textual representations of Geometry are shown in Table 2. The coordinates are shown as integer
values; in general they may be any double precision value.
Note The examples of POINTZ, POINTM, and POINTZM at the bottom of Table 6. This same style for
distinguishing 2D points from 3D points and from 2D or 3D points with M value can be applied to
LINESTRING, POLYGON, MULTIPOINT, MULTILINESTRING, MULTIPOLYGON, and
GEOMETRYCOLLECTION types.`

But then the Table 6 of examples has `Point Z`, `Point ZM` and `Point M` !

So clear guidance is probably needed.

**Comment by chris-little** [comment]
A concrete reason for preferring no spaces before `Z` or `M` is that in the EDR API, the WKT is part of a URL, and we felt that having spaces, which render as %20, was messy.

**Comment by jorisvandenbossche** [comment]
Can you point to where this parameter is described in the EDR API? (to better understand the use case)

**Comment by chris-little** [comment]
The [latest draft version, V1.1](https://opengeospatial.github.io/ogcna-auto-review/19-086r6.html#toc28) Sections 8.2.5, 8.2.6, for the `Trajectory` and `Corridor` queries.
V1.0 and V1.0.1 are the same, though with some mistaken examples.

**Comment by jorisvandenbossche** [comment]
Ah, so in the EDR API case that's about actual WKT reprs of full geometries, not just geometry type indications. Note that in our metadata, this is about the geometry type (so it's not actually WKT, the geometries are stored as WKB)

Looking at https://github.com/opengeospatial/geoparquet/issues/41#issuecomment-1077546595 and comments below that, it seems we went with the current naming scheme based on the types from GeoJSON, and then decided to add "Z" with a space (and not without a space) somewhat randomly (although using the fact that typical WKT strings are using a space as prior art).

**Comment by chris-little** [comment]
And as we are embedding the WKT in URL queries (HTTP(S) GET and POST, saving a few spaces (or %20s) is useful.

**Comment by jorisvandenbossche** [comment]
> And as we are embedding the WKT in URL queries

Yes, but the point I was trying to make is that we don't use WKT at all in the GeoParquet spec. The discussion about what the WKT spec says about spaces is certainly interesting (and relevant for EDR API) and useful to resolve, but thus not that relevant for GeoParquet (and probably should be held elsewhere so the relevant people see it?) 

_If_ the WKT spec would be unambiguous, that would be a useful data point for us to decide whether we want to use a space as well or not. But in the end, our spec (and json schema) for the geometry type is currently explicit in having a space.

**Comment by chris-little** [comment]
@jorisvandenbossche @rouault So I am content that you have addressed the issue for GeoParquet, and highlighted the ambiguity in the WKT spec.
