### ISSUE TITLE
Schema version invalid

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/geoparquet#177]
The version number in the schema is invalid. It is 1.0.0-dev instead of 1.0.0-rc.1

See https://github.com/opengeospatial/geoparquet/releases/download/v1.0.0-rc.1/schema.json

See also: https://github.com/opengeospatial/geoparquet/issues/147#issuecomment-1653306348

**Comment by m-mohr** [comment]
The geoparquet.md also says "1.0.0-dev": https://github.com/opengeospatial/geoparquet/releases/download/v1.0.0-rc.1/geoparquet.md

**Comment by tschaub** [comment]
Yeah, I was just starting to address this.

I wrote up these steps for creating a release: https://github.com/opengeospatial/geoparquet/wiki/Release-Process

These steps include updating the version numbers scattered throughout the repo before creating the release tag.

At this point, I think it would be fine to delete the rc.1 tag and start over with the steps on the above wiki page.

I would do this, except I am wrestling with the python dependencies required by the `scripts` that update the example data and example metadata.  If anybody can update the instructions to get set up to run the python in the `scripts` directory, please do so.

**Comment by kylebarron** [comment]
> I would do this, except I am wrestling with the python dependencies required by the `scripts` that update the example data and example metadata. If anybody can update the instructions to get set up to run the python in the `scripts` directory, please do so.

What's the issue you're hitting here?

**Comment by tschaub** [comment]
Failure to install pyarrow.  It looks like I had a brew installed version of poetry.  Trying again using the poetry installer.

**Comment by m-mohr** [comment]
Great, thanks.

> I wrote up these steps for creating a release: https://github.com/opengeospatial/geoparquet/wiki/Release-Process

Maybe put them in a release.md in the main repo? That's much more common, I never even think that someone uses the Wikis...

**Comment by kylebarron** [comment]
Oh I just tried to install it on my M1 Mac and it failed because it's still using pygeos and that is trying to compile from source for some reason.

Is anyone still using `write_nz_building_outline.py` or can/should we delete it? @cholmes was the only one I knew who was using it I think.

**Comment by tschaub** [comment]
As you may guess, the release process is not entirely ironed out.  I find the wiki easier to edit than creating pull requests for each tweak.  But contributions adding a `release.md` that points to the wiki are welcome.  And when everything is solid, we can get rid of the wiki page in favor of a `release.md` file if people want.

**Comment by tschaub** [comment]
I created #178 with some additional detail on the failure I'm hitting with a "fresh" poetry install.  Not entirely sure how to start over (perhaps I have stale/conflicting/outdated/bad things installed), but I'll keep trying.

**Comment by tschaub** [comment]
https://github.com/opengeospatial/geoparquet/blob/v1.0.0-rc.1/format-specs/schema.json now has the correct version number (updated in https://github.com/opengeospatial/geoparquet/pull/182/commits/6a9c43ef6b8a72e5c56ff12f8f9152062900887f).

**Comment by tschaub** [comment]
No problem, @cholmes.  @m-mohr was right that the release doc on the wiki page was not easy to find - I even forgot having written it.  It was good to tidy up a few things as a result of this.  I think #180 is one thing that warrants further discussion before 1.0.
