### ISSUE TITLE
Support 3D coordinates

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/geoparquet#18]
For this we'll need to decide on [EWKB](https://libgeos.org/specifications/wkb/#extended-wkb) or 
[ISO WKB](https://libgeos.org/specifications/wkb/#iso-wkb)

From what everyone could tell the core WKB is the same with both, so we're starting with that. But we should have experts sound in on what we should use. 

Initial research shows ISO WKB is more of a 'standard', as EWKB has not been formalized in a document (though it has extensive support). With our CRS field we don't actually need the SRID part of EWKB.

**Comment by rouault** [comment]
I would suggest to use ISO WKB.  EWKB is an historical divergent fork, that has added the SRID and used the 25D flag (0x80000000 / most-significant-bit set) for the code of Z geometries, whereas ISO WKB uses a {code_of_2D_geom}+1000 code.
GDAL supports ISO WKB. GeoPackage uses it.
One annoyance with ISO WKB is that there's no official gratis spec for it, but https://github.com/postgis/postgis/blob/master/doc/bnf-wkb.txt can be used by implementors to get the important information.

**Comment by jorisvandenbossche** [comment]
Specifying to use ISO WKB sounds good to me.

Related to https://github.com/opengeospatial/geoparquet/issues/41, we will have to decide if we, for now, only want to officially allow the 3D coordinates part of ISO WKB (which means we would only allow a subset of ISO WKB, and then will need to specify this subset somewhere), or allow any valid ISO WKB value (which also includes M or ZM values, and several Curve and Surface types). 

(personally I would go for just 3D for now)

**Comment by jorisvandenbossche** [comment]
I opened https://github.com/opengeospatial/geoparquet/pull/45 to add this to the spec.
