### ISSUE TITLE
The releases on the repository can be misleading regarding the status of GeoParquet as an OGC Standard

### ISSUE THREAD

**Issue by doublebyte1** [opengeospatial/geoparquet#201]
The releases on this repository refer to the specification, but looking at the way releases are managed in other OGC repositories (e.g.: [JSON-FG](https://github.com/opengeospatial/ogc-feat-geo-json/releases/tag/v0.2.2), [OGC API Tiles](https://github.com/opengeospatial/ogcapi-features/releases/tag/1.0.1) they can be interpreted as versions of the draft standard. 

In this [PR](https://github.com/opengeospatial/geoparquet/pull/200), the README is updated to reflect that this is a draft standard and the releases are not releases of the standard.

**Comment by cholmes** [comment]
Closing this, as there is now language in the main branch of the repo. Let us know if it needs any more adjustment.
