### ISSUE TITLE
Clarify recommended file extension

### ISSUE THREAD

**Issue by kylebarron** [opengeospatial/geoparquet#211]
I've seen a couple instances of users saving files with a `.geoparquet` file extension. We should provide a recommendation of whether this is allowed or whether we recommend all files to be saved with a `.parquet` extension. I don't think this is covered yet in the spec.

**Comment by cholmes** [comment]
Great idea. Would be good to get this in for 1.1 (and I'm realizing we don't have a 1.1 milestone).

Curious on people's thoughts on it? I lean towards just .parquet - fit into the parquet ecosystem as much as possible and don't mess up any other tools that might expect parquet. Only argument I can think the other way is that it's useful to for organizing files to be able to look at them and see they're 'geo'? Wondering if anyone doing this today has strong opinions.

**Comment by rouault** [comment]
Comparison point: everbody publishes GeoTIFF files as ".tif" (or ".tiff" sometimes), but never as ".geotiff"

**Comment by TomAugspurger** [comment]
+1 for `.parquet`. Dask's `read_parquet` uses the file extension to
discover which files under a prefix to read, and (by default) would not
find `*.geoparquet` files:
https://docs.dask.org/en/stable/generated/dask.dataframe.read_parquet.html#dask.dataframe.read_parquet
.

**Comment by hobu** [comment]
"*.cog.tif" and "*.copc.laz" is another convention that is commonly seen. Maybe "*.geo.parquet" could be suggested.

**Comment by jwass** [comment]
Agreed with `.parquet`. One of the advantages of GeoParquet is it's backward-compatible with parquet readers. If we change the extension that would likely break it for a lot of readers.

**Comment by tschaub** [comment]
I also agree that if we recommend anything, it should be `*.parquet`.

**Comment by cholmes** [comment]
I'd say we've got consensus. If anyone wants to write the PR then feel free to claim it (assign to yourself or just comment here) - can get on the 'official' contributor list or up your 'commits contributed' to the spec ;)

**Comment by answerquest** [comment]
> Comparison point: everbody publishes GeoTIFF files as ".tif" (or ".tiff" sometimes), but never as ".geotiff"

.geojson be like shucks why do I exist :rofl: 

chill i'm cool with anything. been saving them as .pqt actually
