### ISSUE TITLE
Enforce pull requests and approvals for all repository updates

### ISSUE THREAD

**Issue by kylebarron** [opengeospatial/geoparquet#216]
I was looking through the recent commit history because I noticed that CI was broken (https://github.com/opengeospatial/geoparquet/pull/214#issuecomment-2107757451) and I noticed that there were two recent commits that were pushed directly to the main branch without a pull request.

<img width="753" alt="image" src="https://github.com/opengeospatial/geoparquet/assets/15164633/8dc8b69e-8ae1-42cb-a06c-6d06063c0752">

In the spirit of openness, I propose that we require a pull request before pushing to main.

I see that in the repository settings we _intend_ to require a pull request before merging
<img width="819" alt="image" src="https://github.com/opengeospatial/geoparquet/assets/15164633/4cd285a3-2858-417c-970b-95b6db833323">

but because the 
<img width="700" alt="image" src="https://github.com/opengeospatial/geoparquet/assets/15164633/5b66aef0-9bf2-44ef-b6e5-a0e26a723185">
box is not checked, this does not apply to people with commit access.

I propose that we enable this box to force all, even administrators, to have at least one approval on a PR.

**Comment by cholmes** [comment]
Thanks for flagging this. I think it's important that every change made to the repo/spec is discussed and approved - it's weird to me to have PR's listed in 'closed' that are merged but not approved. I think we should go further than just requiring this in the future, but should revert these changes and have them go through the process. I'd argue that this process has been a 'community norm', and we shouldn't make an exception for these changes. It should be hard to take them through our process.

**Comment by jorisvandenbossche** [comment]
I have ticked the "Do not allow bypassing the above settings" box

**Comment by kylebarron** [comment]
> I have ticked the "Do not allow bypassing the above settings" box

With that, we can probably close this issue? Or should we leave it open for any more visibility?

**Comment by cholmes** [comment]
+1 to just close the issue.
