### ISSUE TITLE
Require status checks to pass before merging

### ISSUE THREAD

**Issue by kylebarron** [opengeospatial/geoparquet#217]
In light of recent CI failures from https://github.com/opengeospatial/geoparquet/pull/214#issuecomment-2107757451, I propose that we enforce status checks to pass before merging. That is, that we check this box in the repo settings:

<img width="753" alt="image" src="https://github.com/opengeospatial/geoparquet/assets/15164633/a9e2f75b-db31-426e-8a1a-97ac7778ebbb">

We can have a separate discussion over which CI checks _should_ exist. The current main is failing the `trailing-whitespace` and `end-of-file-fixer` checks. These check that there are no tabs or spaces at the end each line (which have no semantic meaning, at least in Markdown or most code languages), and that there is exactly one newline character at the end of the file.

I would argue that these CI checks make a markdown-heavy repository cleaner, and that they should be kept and enforced.

**Comment by cholmes** [comment]
+1

**Comment by kylebarron** [comment]
We could have _more_ markdown linting if people desired: https://github.com/markdownlint/markdownlint

Those two pre-commit checks are little things I have on all my repositories, and so I included them when setting up the pre-commit CI initially. https://github.com/opengeospatial/geoparquet/pull/75

**Comment by m-mohr** [comment]
Same happened in #206

**Comment by kylebarron** [comment]
I updated the branch protection rules for `main` to include the two CI checks. Let me know if anyone has any concerns.

<img width="763" alt="image" src="https://github.com/opengeospatial/geoparquet/assets/15164633/7bdfa5b0-1eee-4b94-813a-4fdafbb61eec">
