### ISSUE TITLE
Make sure examples for 0.1 are valid or removed

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/geoparquet#22]
Right now our 'examples' were made by Tom, and I'm pretty sure are out of date with the tweaks we've made.

If there's code that can make a 0.1 example before we release it'd be great to include. But if not we should just remove the examples (perhaps we could do a 0.1.1 release with examples). If it's too much work to get an example just remove the example folder, or assign to me and I can do it.

**Comment by TomAugspurger** [comment]
I can get the files updated.

**Comment by jorisvandenbossche** [comment]
At the moment, I think it is still a "valid" file. We didn't make incompatible changes to the spec up to now (and the file was already using WKT2 for the crs, and WKB for the geometries, it is only missing some optional fields).

**Comment by TomAugspurger** [comment]
Yep, I think that's right.

I'll wait for https://github.com/opengeospatial/geoparquet/pull/21 to add the bounding box. We might want to include a second example that includes some of the complications raised there.

**Comment by jorisvandenbossche** [comment]
Yes, in general we will want a set of "reference test files" with various cases, I think.

**Comment by cholmes** [comment]
Oh great, we talked through so much that I figured something must have changed, but I guess we mostly reiterated all that we had.

I'll leave this open just to be a final check before releasing 0.1.

**Comment by alasarr** [comment]
@TomAugspurger https://github.com/opengeospatial/geoparquet/pull/21 merged, you can go ahead 💪

**Comment by TomAugspurger** [comment]
Closed by #24. https://github.com/opengeospatial/geoparquet/pull/27 is still open, but the example should be compatible with that.
