### ISSUE TITLE
Create a 'validator' to help implementors check if they are compliant

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/geoparquet#23]
This isn't about the spec itself, but we should track progress towards tools that make it easy to check if a given file is valid GeoParquet. Ideally it'd also give warnings about any best practices - like check for bbox and explain why it's recommended.

It should help any implementor ensure that they are producing what we specified.

I have no idea of the level of effort on this, so if it's easy we can pull it forward in milestones, and it'd be good to have before we try to get lots of implementations.

**Comment by Jesus89** [comment]
Hi, I've added a quick validator Python script using JSON Schema (can be used with other languages too). Please, share your comments and ideas on the draft.

**Comment by Jesus89** [comment]
The PR is merged. There will be more updates in the future regarding the validator, but I think we can close this one because the first version has been merged.
