### ISSUE TITLE
Use RFC 2119 definitions of MUST, SHOULD, etc.?

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/geoparquet#26]
A number of specs specifically say something like: 

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt) See [mbtiles spec](https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md#abstract). for example.

Should we do the same? And go through our language to make sure it matches? I'm not sure that we ever did this for STAC. But I think OGC specs usually do.

I don't feel strongly, but making an issue so we discuss and track.

**Comment by m-mohr** [comment]
STAC tries to use this, but did never fully embrace it due to the amount of text.
Here it could be feasible as the spec is much more lightweight, so +1.
