### ISSUE TITLE
File level metadata field names

### ISSUE THREAD

**Issue by pomadchin** [opengeospatial/geoparquet#30]
At this point the we propose to store metadata at the very top level:
i.e. 

```python
metadata = {
    "version": "0.1.0",
    "primary_column": "geometry",
    "columns": {
        "geometry": {
            "crs": df.crs.to_wkt(pyproj.enums.WktVersion.WKT2_2019_SIMPLIFIED),
            "encoding": "WKB",
        }
    }
}
```

What if there is a metadata field names overlap with other libraries?

As a solution to this issue we can prefix all geoparquet fields, i.e.

```python
metadata = {
    "geoparquet.version": "0.1.0",
    "geoparquet.primary_column": "geometry",
    "geoparquet.columns": {
        "geometry": {
            "crs": df.crs.to_wkt(pyproj.enums.WktVersion.WKT2_2019_SIMPLIFIED),
            "encoding": "WKB",
        }
    }
}
```

Or make the metadata nested:

```python
metadata = {
    "geoparquet": {
        "version": "0.1.0",
        "primary_column": "geometry",
        "columns": {
            "geometry": {
                "crs": df.crs.to_wkt(pyproj.enums.WktVersion.WKT2_2019_SIMPLIFIED),
                "encoding": "WKB",
            }
        }
    }
}
```

i.e. Spark resolves everything by putting extra metadata into the `spark` prefixed fields.

**Comment by jorisvandenbossche** [comment]
The current spec says to put them all under a "geo" key (so like your last example, but with "geo" as name):

https://github.com/opengeospatial/geoparquet/blob/183a934a4f6887b7277e335ec5ca20633c203e6a/format-specs/geoparquet.md?plain=1#L23

See also the example code:

https://github.com/opengeospatial/geoparquet/blob/183a934a4f6887b7277e335ec5ca20633c203e6a/examples/geoparquet/example.py#L56

**Comment by pomadchin** [comment]
@jorisvandenbossche 🤦 thx!
