### ISSUE TITLE
Should this repo have a license?

### ISSUE THREAD

**Issue by jorisvandenbossche** [opengeospatial/geoparquet#37]
I think the answer is yes, and I assume we pick one of MIT / Apache / BSD ?

(eg stac-spec uses Apache: https://github.com/radiantearth/stac-spec/blob/master/LICENSE)

**Comment by cholmes** [comment]
Oh yeah, we need to do that. Perhaps even worth a 0.1.1 release?

I'm +1 on permissive, agree MIT / Apache / BSD are the choices. I tend to default to Apache.

**Comment by cholmes** [comment]
That makes sense and is fine for me.

**Comment by cholmes** [comment]
PR up at #38. Just did Apache, github seems to recommend either apache or MIT. Happy for an alternative.

Did copyright to OGC, since we're working under their repo and they're a good neutral organization.

**Comment by jorisvandenbossche** [comment]
Sounds good!
