### ISSUE TITLE
Store JSON copy of metadata next to example Parquet files

### ISSUE THREAD

**Issue by kylebarron** [opengeospatial/geoparquet#65]
Making a separate issue to follow up on https://github.com/opengeospatial/geoparquet/pull/60#discussion_r848664664

I propose that for our examples we include a JSON file next to each Parquet file that mirrors its metadata. For example:

```bash
example1.parquet
# plain text schema that matches what's stored in example1.parquet
example1_schema.json

example2.parquet
# plain text schema that matches what's stored in example2.parquet
example2_schema.json
```

Benefits:

- Should make it easier for people browsing the spec to see schema examples without needing to open up a file.
- Git diffs should be easier to read and understand. Note that this requires that JSON files are always formatted in the same way, which we could enforce via a CI lint step.

We should also have a CI step that verifies the plain text schema in `example1_schema.json` actually matches what's actually stored in `example1.parquet`, and ideally that the schema passes validation (see #64 and #58)

**Comment by cholmes** [comment]
+1 - seems like it'll make it much easier for people to see what's going on. And definitely +1 on CI to check formatting and that the plain text schema matches its example.
