### ISSUE TITLE
Add script functionality to update parquet binaries from JSON examples

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/geoparquet#69]
I think it can be useful to have the opposite function too: read the JSON file and update the parquet file. This can speed up the updates while developing new versions of the spec.

_Originally posted by @Jesus89 in https://github.com/opengeospatial/geoparquet/pull/68#discussion_r851955101_

**Comment by kylebarron** [comment]
I think you want the order of the issue title reversed 😄

**Comment by cholmes** [comment]
Whoops. Thanks @Jesus89 for fixing.
